### ISSUE TITLE
Text chat

### ISSUE THREAD

**Issue by ghu7994** [doc19org/medicam#9]
Add a simple text chat feature as a fallback if there are video or audio issues. We can probably use Twilio's chat API for this.

**Comment by bryanaka** [comment]
Leaving this here as a relevant reference blog post

https://www.twilio.com/blog/2018/05/build-chat-python-django-applications-programmable-chat.html

**Comment by bryanaka** [comment]
I feel like any retained text information (including chat) may be the most "risky" part of the project due to PHI. Twilio even mentions considering PHI since they retain chat data.

So two thoughts:
1. Is encryption before hitting Twilio possible and if so, enough to satisfy HIPAA concerns?
2. If not, does it make more sense to stand up something ourselves that is encrypted and more ephemeral so that we control any potential PHI?

https://www.twilio.com/docs/chat/secure-and-scale-programmable-chat-applications#follow-the-law-get-the-users-consent

I will also do more digging into HIPAA. I know laws have been somewhat relaxed in this climate, so we got that.

**Comment by ghughes** [comment]
I believe some of Twilio’s APIs can be considered HIPAA compliant because they’ll sign a BAA if you pay them a ton of money, but the catch is that not all of their products are covered. Video is, but it’s unclear to me whether chat is covered. I agree that it might be better for us to do it in-house, since we don’t need any fancy features and we also need #8 anyway.

**Comment by ghu7994** [comment]
Barebones implementation of this is done.
